spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security_login
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  security:
    jwt:
      secret-key: secret-key # https://generate-random.org/encryption-key-generator
      expiration: 60000 #one min
      refresh-token:
        expiration: 3600000 #one h